const GOLD = "#f0c020"
export const LEVELS = [
  {
    id: "lv1",
    number: 1,
    name: "THE IRON PIT",
    subtitle: "Training Grounds",
    description:
      "A derelict underground arena carved from rust and bone. Beginners bleed here first.",
    difficulty: 1,
    color: "#44aaff",
    bgSrc: "/stages/1.jpg",
    accentColor: "#aaddff",
    bg: "radial-gradient(ellipse 80% 60% at 50% 80%, #001133 0%, #070810 70%)",
    pattern: "grid",
    icon: "⚔️",
    tags: ["STARTER", "FLAT TERRAIN"],
  },
  {
    id: "lv2",
    number: 2,
    name: "CRIMSON THRONE",
    subtitle: "Palace of Blood",
    description:
      "Once a royal court, now soaked in the crimson of a thousand duels. Only champions enter.",
    difficulty: 2,
    color: "#e8001a",
    accentColor: "#ff6644",
    bg: "radial-gradient(ellipse 80% 60% at 50% 80%, #2a0000 0%, #070810 70%)",
    bgSrc: "/stages/2.jpg",
    pattern: "diagonal",
    icon: "👑",
    tags: ["INTERMEDIATE", "ELEVATED PLATFORMS"],
  },
  {
    id: "lv3",
    number: 3,
    name: "VOID NEXUS",
    subtitle: "Edge of Oblivion",
    description:
      "A rift suspended between dimensions. Reality tears at the seams. Fall and cease to exist.",
    difficulty: 3,
    color: "#9933cc",
    accentColor: "#cc66ff",
    bg: "radial-gradient(ellipse 80% 60% at 50% 80%, #1a0033 0%, #070810 70%)",
    bgSrc: "/stages/3.jpg",
    pattern: "dots",
    icon: "🌌",
    tags: ["ADVANCED", "HAZARDS ACTIVE"],
  },
  {
    id: "lv4",
    number: 4,
    name: "Kefka's Stadium",
    subtitle: "Final Battlefield",
    description:
      "The last garden before the unknown. Petals have withered and bloomed again here. Are you ready to step among them?",
    difficulty: 4,
    color: "#008000",
    accentColor: "#fff",
    bgSrc: "/stages/4.jpg",
    bg: "radial-gradient(ellipse 80% 60% at 50% 80%, #221200 0%, #070810 70%)",
    pattern: "grid",
    icon: "🌸",
    tags: ["LEGENDARY", "ALL HAZARDS"],
  },
  {
    id: "lv5",
    number: 5,
    name: "SOLAR FORGE",
    subtitle: "Heart of the Sun",
    description:
      "A crucible of raw stellar fire. The arena itself burns. Only the worthy survive the heat.",
    difficulty: 5,
    color: "#ff8800",
    bgSrc: "/stages/5.jpg",
    accentColor: "#ffcc44",
    bg: "radial-gradient(ellipse 80% 60% at 50% 80%, #2a1000 0%, #070810 70%)",
    pattern: "diagonal",
    icon: "☀️",
    tags: ["EXPERT", "MOVING STAGE"],
  },
  {
    id: "lv6",
    number: 6,
    name: "OMEGA SANCTUM",
    subtitle: "Final Battlefield",
    description:
      "The last arena before the abyss. Gods and demons have fallen here. Are you prepared?",
    difficulty: 6,
    color: GOLD,
    accentColor: "#fff",
    bg: "radial-gradient(ellipse 80% 60% at 50% 80%, #221200 0%, #070810 70%)",
    bgSrc: "/stages/6.jpg",
    pattern: "grid",
    icon: "💀",
    tags: ["LEGENDARY", "ALL HAZARDS"],
  },
]
